ops:
  master:
    hostname: "192.168.2.11"
    port_grpc: 14010
  worker:
    localDir: "/home/root/tmp_OPS/"
    port_grpc: 14020
    port_hadoop_grpc: 14030

etcd:
  endpoints:
    - "http://192.168.2.11:2379"
    - "http://192.168.2.12:2379"
    - "http://192.168.2.13:2379"
